services:
  wordpress:
    build: ../
    ports:
      - "8080:80"
    volumes:
      - wp-data:/var/www/html/wp-content
    env_file:
      - ../.env.local
    depends_on:
      - mysql
  mysql:
    image: mysql:8.1.0
    env_file:
      - ../.env.local
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    ports:
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
  wp-data:
